### ISSUE TITLE
Let Google pybigquery project use the sqlalchemy-bigquery name in PyPI

### ISSUE THREAD

**Issue by jimfulton** [cpdean/sqlalchemy-bigquery#7]
Hi,

The [pybigquery](https://github.com/googleapis/python-bigquery-sqlalchemy) project has a mature and complete SQLAlchemy dialect implementation for BigQuery.

We'd like to re-release this under the sqlalchemy-bigquery name, to conform to SQLAlchemy dialect-naming conventions.

As this project doesn't appear to be active, we're requesting that you let is take over the PyPI project.

**Comment by cpdean** [comment]
added redirect which supports the work in the transition for https://github.com/googleapis/python-bigquery-sqlalchemy/pull/198
